
website:
  title: "Alejandro Frydman"
  image: img/headshot.jpg
  
  favicon: img/mit_logo.png
  search: false
  # start of the navication bar at the top of the website
  navbar:
    pinned: true
    # Top left corner logo
    
    background: primary

    # Sub-pages
    right:
    - text: "Research"
      href: research/research.qmd
    - text: "CV"
      href: cv/cv.qmd
      

    
       

project:
  type: website
  output-dir: docs

  preview:
    port: 22222
    browser: true
    watch-inputs: true
    navigate: true

execute:
  freeze: true
  
format:
  html:
    theme: yeti
    css: styles.css
    toc: false
    page-layout: full


